#!/usr/bin/env jake
'use strict';

const testLab = require('./suite/testlab.integration.spec').taskList;

const tests = [
  ...testLab,
];

task('default', tests, () => {
  console.log('All done.');
});
